/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;
import javax.swing.JFrame;
import java.sql.ResultSetMetaData;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JTable;
import java.lang.NumberFormatException;
/**
 *
 * @author Thivanka_Mihiranga
 */
public class SecondryStudentMarks extends javax.swing.JFrame {
private JFrame Frame;
Connection conn;
PreparedStatement pst;
PreparedStatement pst1;
ResultSet rs;
    /**
     * Creates new form SecondryStudentMarks
     */
    public SecondryStudentMarks() {
        initComponents();
        table_update();
        getData();
    }
public void getData()
{
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            pst1 = conn.prepareStatement("SELECT * FROM secoundrystudent");
            rs=pst1.executeQuery();
            
            jtxtSID.removeAllItems();
            
            
            while(rs.next())
            {
                jtxtSID.addItem(rs.getString(1)+" "+rs.getString(2));
                
            }
        
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondryStudentMarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
                Logger.getLogger(SecondryStudentMarks.class.getName()).log(Level.SEVERE, null, ex);
            }
                 

}
private void table_update()
    {
        int c;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            pst = conn.prepareStatement("SELECT * FROM SSM2");
            ResultSet rs=pst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df= (DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
            
            while (rs.next())
            {
            Vector v2 =new Vector();
            
            for(int a=1;a<=c;a++)
            {
            v2.add(rs.getString("SID"));
            v2.add(rs.getString("Addmission"));
            v2.add(rs.getString("S1M"));
            v2.add(rs.getString("S1G"));
            v2.add(rs.getString("S2M"));
            v2.add(rs.getString("S2G"));
            v2.add(rs.getString("S3M"));
            v2.add(rs.getString("S3G"));
            v2.add(rs.getString("S4M"));
            v2.add(rs.getString("S4G"));
            v2.add(rs.getString("S5M"));
            v2.add(rs.getString("S5G"));
            v2.add(rs.getString("S6M"));
            v2.add(rs.getString("S6G"));
            v2.add(rs.getString("S7M"));
            v2.add(rs.getString("S7G"));
            v2.add(rs.getString("S8M"));
            v2.add(rs.getString("S8G"));
            v2.add(rs.getString("S9M"));
            v2.add(rs.getString("S9G"));
            v2.add(rs.getString("Total"));
            v2.add(rs.getString("AVG"));
            }
            Df.addRow(v2);
            }
                    
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(SecondryStudentMarks.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtSID = new javax.swing.JComboBox<>();
        jtxtAddmissin = new javax.swing.JTextField();
        jtxtSM1 = new javax.swing.JTextField();
        jtxtSM2 = new javax.swing.JTextField();
        jtxtSM3 = new javax.swing.JTextField();
        jtxtSM4 = new javax.swing.JTextField();
        jtxtSM5 = new javax.swing.JTextField();
        jtxtSG1 = new javax.swing.JTextField();
        jtxtSG2 = new javax.swing.JTextField();
        jtxtSG3 = new javax.swing.JTextField();
        jtxtSG4 = new javax.swing.JTextField();
        jtxtSG5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbtnGen = new javax.swing.JButton();
        jtxtAvg = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtSG7 = new javax.swing.JTextField();
        jtxtSM7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtSM8 = new javax.swing.JTextField();
        jtxtSG8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtSG9 = new javax.swing.JTextField();
        jtxtSM9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtSM6 = new javax.swing.JTextField();
        jtxtSG6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnPrint = new javax.swing.JButton();
        jbtnHome = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(930, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtSID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 260, -1));

        jtxtAddmissin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtAddmissin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, -1));

        jtxtSM1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, -1));

        jtxtSM2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 90, -1));

        jtxtSM3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, -1));

        jtxtSM4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, -1));

        jtxtSM5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 90, -1));

        jtxtSG1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG1.setEnabled(false);
        jtxtSG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSG1MouseClicked(evt);
            }
        });
        jPanel1.add(jtxtSG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 90, -1));

        jtxtSG2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG2.setEnabled(false);
        jPanel1.add(jtxtSG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 90, -1));

        jtxtSG3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG3.setEnabled(false);
        jPanel1.add(jtxtSG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, -1));

        jtxtSG4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG4.setEnabled(false);
        jPanel1.add(jtxtSG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 90, -1));

        jtxtSG5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG5.setEnabled(false);
        jtxtSG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSG5ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtSG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 90, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SID & Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Addmission No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject 5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject 4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subject 3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subject 2");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Subject 1");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, -1, 30));

        jbtnGen.setBackground(new java.awt.Color(51, 102, 255));
        jbtnGen.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnGen.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/loading.png"))); // NOI18N
        jbtnGen.setText("Genarate");
        jbtnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 160, 90));

        jtxtAvg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtAvg.setEnabled(false);
        jPanel1.add(jtxtAvg, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 110, -1));

        jtxtTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtTotal.setEnabled(false);
        jPanel1.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 110, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Average");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Marks");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, 30));

        jtxtSG7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG7.setEnabled(false);
        jPanel1.add(jtxtSG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 90, -1));

        jtxtSM7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 90, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Subject 7");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Subject 8");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, 30));

        jtxtSM8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 90, -1));

        jtxtSG8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG8.setEnabled(false);
        jPanel1.add(jtxtSG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 90, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Subject 9");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 80, 30));

        jtxtSG9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG9.setEnabled(false);
        jPanel1.add(jtxtSG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 90, -1));

        jtxtSM9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 90, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Subject 6");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        jtxtSM6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtSM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 90, -1));

        jtxtSG6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtSG6.setEnabled(false);
        jtxtSG6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSG6ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtSG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 90, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SID", "Addmissin", "S1M", "S1G", "S2M", "S2G", "S3M", "S3G", "S4M", "S4G", "S5M", "S5G", "S6M", "S6G", "S7M", "S7G", "S8M", "S8G", "S9M", "S9G", "Total", "AVG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 910, 180));

        jbtnPrint.setBackground(new java.awt.Color(51, 102, 255));
        jbtnPrint.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnPrint.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/printer.png"))); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 170, 70));

        jbtnHome.setBackground(new java.awt.Color(51, 102, 255));
        jbtnHome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jbtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/house.png"))); // NOI18N
        jbtnHome.setText("Home");
        jbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 170, 70));

        jbtnExit.setBackground(new java.awt.Color(51, 102, 255));
        jbtnExit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exit.png"))); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 170, 70));

        jbtnDelete.setBackground(new java.awt.Color(51, 102, 255));
        jbtnDelete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/delete.png"))); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 170, 70));

        jbtnReset.setBackground(new java.awt.Color(51, 102, 255));
        jbtnReset.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/reset.png"))); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 170, 70));

        jbtnUpdate.setBackground(new java.awt.Color(51, 102, 255));
        jbtnUpdate.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/update.png"))); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 170, 70));

        jbtnSubmit.setBackground(new java.awt.Color(51, 102, 255));
        jbtnSubmit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jbtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/submit.png"))); // NOI18N
        jbtnSubmit.setText("Submit");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 170, 70));

        jLabel1.setFont(new java.awt.Font("Uglygoodbaddark", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secondry Student Marks");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 620, 56));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/wallpaperflare.com_wallpaper (41).jpg"))); // NOI18N
        jLabel4.setText("jLabel3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtSG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSG1MouseClicked
        //
    }//GEN-LAST:event_jtxtSG1MouseClicked

    private void jtxtSG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSG5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSG5ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtSID.setSelectedIndex(-1);
            jtxtAddmissin.setText("");
            jtxtSM1.setText("");
            jtxtSM2.setText("");
            jtxtSM3.setText("");
            jtxtSM4.setText("");
            jtxtSM5.setText("");
            jtxtSG1.setText("");
            jtxtSG2.setText("");
            jtxtSG3.setText("");
            jtxtSG4.setText("");
            jtxtSG5.setText("");
            jtxtSM6.setText("");
            jtxtSM7.setText("");
            jtxtSM8.setText("");
            jtxtSM9.setText("");
            jtxtSG6.setText("");
            jtxtSG7.setText("");
            jtxtSG8.setText("");
            jtxtSG9.setText("");
            jtxtTotal.setText("");
            jtxtAvg.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        String SID = jtxtSID.getSelectedItem().toString();
        String Addmission = jtxtAddmissin.getText();
        String S1M = jtxtSM1.getText();
        String S1G = jtxtSG1.getText();
        String S2M = jtxtSM2.getText();
        String S2G = jtxtSG2.getText();
        String S3M = jtxtSM3.getText();
        String S3G = jtxtSG3.getText();
        String S4M = jtxtSM4.getText();
        String S4G = jtxtSG4.getText();
        String S5M = jtxtSM5.getText();
        String S5G = jtxtSG5.getText();
        String S6M = jtxtSM6.getText();
        String S6G = jtxtSG6.getText();
        String S7M = jtxtSM7.getText();
        String S7G = jtxtSG7.getText();
        String S8M = jtxtSM8.getText();
        String S8G = jtxtSG8.getText();
        String S9M = jtxtSM9.getText();
        String S9G = jtxtSG9.getText();
        String Total = jtxtTotal.getText();
        String AVG = jtxtAvg.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            pst = conn.prepareStatement("INSERT INTO SSM2(SID,Addmission ,S1M,S1G,S2M,S2G,S3M,S3G,S4M,S4G,S5M,S5G,"
                    + "S6M,S6G,S7M,S7G,S8M,S8G,S9M,S9G,Total,AVG)"
                + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,SID );
            pst.setString(2,Addmission );
            pst.setString(3,S1M );
            pst.setString(4,S1G );
            pst.setString(5,S2M );
            pst.setString(6,S2G );
            pst.setString(7,S3M );
            pst.setString(8,S3G );
            pst.setString(9,S4M );
            pst.setString(10,S4G );
            pst.setString(11,S5M );
            pst.setString(12,S5G );
            pst.setString(13,S6M );
            pst.setString(14,S6G );
            pst.setString(15,S7M );
            pst.setString(16,S7G );
            pst.setString(17,S8M );
            pst.setString(18,S8G );
            pst.setString(19,S9M );
            pst.setString(20,S9G );
            pst.setString(21,Total );
            pst.setString(22,AVG);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "User Was Added.....");

            table_update();

            jtxtSID.setSelectedIndex(-1);
            jtxtAddmissin.setText("");
            jtxtSM1.setText("");
            jtxtSM2.setText("");
            jtxtSM3.setText("");
            jtxtSM4.setText("");
            jtxtSM5.setText("");
            jtxtSG1.setText("");
            jtxtSG2.setText("");
            jtxtSG3.setText("");
            jtxtSG4.setText("");
            jtxtSG5.setText("");
            jtxtSM6.setText("");
            jtxtSM7.setText("");
            jtxtSM8.setText("");
            jtxtSM9.setText("");
            jtxtSG6.setText("");
            jtxtSG7.setText("");
            jtxtSG8.setText("");
            jtxtSG9.setText("");
            jtxtTotal.setText("");
            jtxtAvg.setText("");

            jtxtSID.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondryStudentMarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        DefaultTableModel Df= (DefaultTableModel)jTable1.getModel();
        int SelectedIndex=jTable1.getSelectedRow();

        try {
            int Addmission=Integer.parseInt(Df.getValueAt(SelectedIndex, 1).toString());
            String SID = jtxtSID.getSelectedItem().toString();
            String S1M = jtxtSM1.getText();
            String S1G = jtxtSG1.getText();
            String S2M = jtxtSM2.getText();
            String S2G = jtxtSG2.getText();
            String S3M = jtxtSM3.getText();
            String S3G = jtxtSG3.getText();
            String S4M = jtxtSM4.getText();
            String S4G = jtxtSG4.getText();
            String S5M = jtxtSM5.getText();
            String S5G = jtxtSG5.getText();
            String S6M = jtxtSM6.getText();
            String S6G = jtxtSG6.getText();
            String S7M = jtxtSM7.getText();
            String S7G = jtxtSG7.getText();
            String S8M = jtxtSM8.getText();
            String S8G = jtxtSG8.getText();
            String S9M = jtxtSM9.getText();
            String S9G = jtxtSG9.getText();
            String Total = jtxtTotal.getText();
            String AVG = jtxtAvg.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            pst = conn.prepareStatement("UPDATE ssm2 SET SID= ?,S1M= ?,S1G=?,S2M=?,S2G=?,S3M=?"
                + ",S3G=?,S4M=?,S4G=?,S5M=?,S5G=?,S6M=?,S6G=?,S7M=?,S7G=?,"
                    + "S8M=?,S8G=?,S9M=?,S9G=?,Total=?,AVG=? WHERE Addmission=?");
            pst.setString(1,SID );
            pst.setInt(22,Addmission );
            pst.setString(2,S1M );
            pst.setString(3,S1G );
            pst.setString(4,S2M );
            pst.setString(5,S2G );
            pst.setString(6,S3M );
            pst.setString(7,S3G );
            pst.setString(8,S4M );
            pst.setString(9,S4G );
            pst.setString(10,S5M );
            pst.setString(11,S5G );
            pst.setString(12,S6M );
            pst.setString(13,S6G );
            pst.setString(14,S7M );
            pst.setString(15,S7G );
            pst.setString(16,S8M );
            pst.setString(17,S8G );
            pst.setString(18,S9M );
            pst.setString(19,S9G );
            pst.setString(20,Total );
            pst.setString(21,AVG );

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "User Was UPDATED.....");

            table_update();

            jtxtSID.setSelectedIndex(-1);
            jtxtAddmissin.setText("");
            jtxtSM1.setText("");
            jtxtSM2.setText("");
            jtxtSM3.setText("");
            jtxtSM4.setText("");
            jtxtSM5.setText("");
            jtxtSG1.setText("");
            jtxtSG2.setText("");
            jtxtSG3.setText("");
            jtxtSG4.setText("");
            jtxtSG5.setText("");
            jtxtSM6.setText("");
            jtxtSM7.setText("");
            jtxtSM8.setText("");
            jtxtSM9.setText("");
            jtxtSG6.setText("");
            jtxtSG7.setText("");
            jtxtSG8.setText("");
            jtxtSG9.setText("");
            jtxtTotal.setText("");
            jtxtAvg.setText("");

            jtxtSID.requestFocus();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondryStudentMarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel Df= (DefaultTableModel)jTable1.getModel();
        int SelectedIndex=jTable1.getSelectedRow();

        try {
            int Addmission=Integer.parseInt(Df.getValueAt(SelectedIndex, 1).toString());

            int Dialog = JOptionPane.showConfirmDialog(null,"Do You Want To Delete The Record?","Warning",JOptionPane.YES_NO_OPTION);
            if (Dialog == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
                pst = conn.prepareStatement("DELETE FROM `SSM2` WHERE `SSM2`.`Addmission` = ?");
                pst.setInt(1,Addmission );
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "User Was Deleted.....");

                table_update();

                jtxtSID.setSelectedIndex(-1);
            jtxtAddmissin.setText("");
            jtxtSM1.setText("");
            jtxtSM2.setText("");
            jtxtSM3.setText("");
            jtxtSM4.setText("");
            jtxtSM5.setText("");
            jtxtSG1.setText("");
            jtxtSG2.setText("");
            jtxtSG3.setText("");
            jtxtSG4.setText("");
            jtxtSG5.setText("");
            jtxtSM6.setText("");
            jtxtSM7.setText("");
            jtxtSM8.setText("");
            jtxtSM9.setText("");
            jtxtSG6.setText("");
            jtxtSG7.setText("");
            jtxtSG8.setText("");
            jtxtSG9.setText("");
            jtxtTotal.setText("");
            jtxtAvg.setText("");
            
            jtxtSID.requestFocus();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SecondryStudentMarks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHomeActionPerformed
        Home m = new Home();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jbtnHomeActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header=new MessageFormat("Senior Student Details");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");

        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        Frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog( Frame,"confirm if you Want to Exit","Name of the Application or Title",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel Df= (DefaultTableModel)jTable1.getModel();
        int SelectedIndex=jTable1.getSelectedRow();

        jtxtSID.setSelectedIndex(0);
        jtxtAddmissin.setText(Df.getValueAt(SelectedIndex,1).toString());
        jtxtSM1.setText(Df.getValueAt(SelectedIndex,2).toString());
        jtxtSG1.setText(Df.getValueAt(SelectedIndex,3).toString());
        jtxtSM2.setText(Df.getValueAt(SelectedIndex,4).toString());
        jtxtSG2.setText(Df.getValueAt(SelectedIndex,5).toString());
        jtxtSM3.setText(Df.getValueAt(SelectedIndex,6).toString());
        jtxtSG3.setText(Df.getValueAt(SelectedIndex,7).toString());
        jtxtSM4.setText(Df.getValueAt(SelectedIndex,8).toString());
        jtxtSG4.setText(Df.getValueAt(SelectedIndex,9).toString());
        jtxtSM5.setText(Df.getValueAt(SelectedIndex,10).toString());
        jtxtSG5.setText(Df.getValueAt(SelectedIndex,11).toString());
        jtxtSM6.setText(Df.getValueAt(SelectedIndex,12).toString());
        jtxtSG6.setText(Df.getValueAt(SelectedIndex,13).toString());
        jtxtSM7.setText(Df.getValueAt(SelectedIndex,14).toString());
        jtxtSG7.setText(Df.getValueAt(SelectedIndex,15).toString());
        jtxtSM8.setText(Df.getValueAt(SelectedIndex,16).toString());
        jtxtSG8.setText(Df.getValueAt(SelectedIndex,17).toString());
        jtxtSM9.setText(Df.getValueAt(SelectedIndex,18).toString());
        jtxtSG9.setText(Df.getValueAt(SelectedIndex,19).toString());
        jtxtTotal.setText(Df.getValueAt(SelectedIndex,20).toString());
        jtxtAvg.setText(Df.getValueAt(SelectedIndex,21).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenActionPerformed

        int s1m =Integer.parseInt(jtxtSM1.getText());
        {if (s1m>100 || s1m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 1");
        else
            if (s1m>=75)
                jtxtSG1.setText("A");
                else
                if (s1m>=65)
                jtxtSG1.setText("B");
                else
                if (s1m>=55)
                jtxtSG1.setText("C");
                else
                if (s1m>=35)
                jtxtSG1.setText("S");
                else
                jtxtSG1.setText("W");
        }

        int s2m =Integer.parseInt(jtxtSM2.getText());
        {if (s2m>100 || s2m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 2");
        else
            if (s2m>=75)
                jtxtSG2.setText("A");
                else
                if (s2m>=65)
                jtxtSG2.setText("B");
                else
                if (s2m>=55)
                jtxtSG2.setText("C");
                else
                if (s2m>=35)
                jtxtSG2.setText("S");
                else
                jtxtSG2.setText("W");
        }

        int s3m =Integer.parseInt(jtxtSM3.getText());
        {if (s3m>100 || s3m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 3");
        else
            if (s3m>=75)
                jtxtSG3.setText("A");
                else
                if (s3m>=65)
                jtxtSG3.setText("B");
                else
                if (s3m>=55)
                jtxtSG3.setText("C");
                else
                if (s3m>=35)
                jtxtSG3.setText("S");
                else
                jtxtSG3.setText("W");
        }

        int s4m =Integer.parseInt(jtxtSM4.getText());
        {if (s4m>100 || s4m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 4");
        else
            if (s4m>=75)
                jtxtSG4.setText("A");
                else
                if (s4m>=65)
                jtxtSG4.setText("B");
                else
                if (s4m>=55)
                jtxtSG4.setText("C");
                else
                if (s4m>=35)
                jtxtSG4.setText("S");
                else
                jtxtSG4.setText("W");
        }

        int s5m =Integer.parseInt(jtxtSM5.getText());
        {if (s5m>100 || s5m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 5");
        else
            if (s5m>=75)
                jtxtSG5.setText("A");
                else
                if (s5m>=65)
                jtxtSG5.setText("B");
                else
                if (s5m>=55)
                jtxtSG5.setText("C");
                else
                if (s5m>=35)
                jtxtSG5.setText("S");
                else
                jtxtSG5.setText("W");
        }
        int s6m =Integer.parseInt(jtxtSM6.getText());
        {if (s6m>100 || s6m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 6");
        else
            if (s6m>=75)
                jtxtSG6.setText("A");
                else
                if (s6m>=65)
                jtxtSG6.setText("B");
                else
                if (s6m>=55)
                jtxtSG6.setText("C");
                else
                if (s6m>=35)
                jtxtSG6.setText("S");
                else
                jtxtSG6.setText("W");
        }

        int s7m =Integer.parseInt(jtxtSM7.getText());
        {if (s7m>100 || s7m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 7");
        else
            if (s7m>=75)
                jtxtSG7.setText("A");
                else
                if (s7m>=65)
                jtxtSG7.setText("B");
                else
                if (s7m>=55)
                jtxtSG7.setText("C");
                else
                if (s7m>=35)
                jtxtSG7.setText("S");
                else
                jtxtSG7.setText("W");
        }

        int s8m =Integer.parseInt(jtxtSM8.getText());
        {if (s8m>100 || s8m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 8");
        else
            if (s8m>=75)
                jtxtSG8.setText("A");
                else
                if (s8m>=65)
                jtxtSG8.setText("B");
                else
                if (s8m>=55)
                jtxtSG8.setText("C");
                else
                if (s8m>=35)
                jtxtSG8.setText("S");
                else
                jtxtSG8.setText("W");
        }

        int s9m =Integer.parseInt(jtxtSM9.getText());
        {if (s9m>100 || s9m<0)
            JOptionPane.showMessageDialog(null, "Enter 0-100 Range Value as input For Subject 9");
        else
            if (s9m>=75)
                jtxtSG9.setText("A");
                else
                if (s9m>=65)
                jtxtSG9.setText("B");
                else
                if (s9m>=55)
                jtxtSG9.setText("C");
                else
                if (s9m>=35)
                jtxtSG9.setText("S");
                else
                jtxtSG9.setText("W");
        }
        float Total=(s1m+s2m+s3m+s4m+s5m+s6m+s7m+s8m+s9m);
        String str1 = Float.toString(Total);
        jtxtTotal.setText(str1);

        float Avg;
        Avg = 0.00f;
        Avg=(Total/9);
        String str2 = Float.toString(Avg);
        jtxtAvg.setText(str2);
    }//GEN-LAST:event_jbtnGenActionPerformed

    private void jtxtSG6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSG6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSG6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondryStudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondryStudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondryStudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondryStudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondryStudentMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGen;
    private javax.swing.JButton jbtnHome;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAddmissin;
    private javax.swing.JTextField jtxtAvg;
    private javax.swing.JTextField jtxtSG1;
    private javax.swing.JTextField jtxtSG2;
    private javax.swing.JTextField jtxtSG3;
    private javax.swing.JTextField jtxtSG4;
    private javax.swing.JTextField jtxtSG5;
    private javax.swing.JTextField jtxtSG6;
    private javax.swing.JTextField jtxtSG7;
    private javax.swing.JTextField jtxtSG8;
    private javax.swing.JTextField jtxtSG9;
    private javax.swing.JComboBox<String> jtxtSID;
    private javax.swing.JTextField jtxtSM1;
    private javax.swing.JTextField jtxtSM2;
    private javax.swing.JTextField jtxtSM3;
    private javax.swing.JTextField jtxtSM4;
    private javax.swing.JTextField jtxtSM5;
    private javax.swing.JTextField jtxtSM6;
    private javax.swing.JTextField jtxtSM7;
    private javax.swing.JTextField jtxtSM8;
    private javax.swing.JTextField jtxtSM9;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
