/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;
import java.awt.Component;
import java.awt.Frame;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Thivanka_Mihiranga
 */
public class Student2 extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
PreparedStatement pst1;
ResultSet rs;
ResultSet rs2;
    private JFrame Frame;
    /**
     * Creates new form Student2
     */
    public Student2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtAdm = new javax.swing.JTextField();
        jtxtSID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtStudentMarks = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtStudentDetails = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(930, 710));
        jPanel1.setMinimumSize(new java.awt.Dimension(930, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAdmActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 220, 40));
        jPanel1.add(jtxtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 210, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Addmission No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 220, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Student ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, 40));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/seo.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 60));

        jtxtStudentMarks.setColumns(20);
        jtxtStudentMarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtStudentMarks.setRows(5);
        jtxtStudentMarks.setEnabled(false);
        jScrollPane3.setViewportView(jtxtStudentMarks);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 430, 460));

        jtxtStudentDetails.setColumns(20);
        jtxtStudentDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtStudentDetails.setRows(5);
        jtxtStudentDetails.setEnabled(false);
        jScrollPane4.setViewportView(jtxtStudentDetails);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 440, 460));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exit.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 160, 60));

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cleaning.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 160, 60));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/printer.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, 60));

        jButton5.setBackground(new java.awt.Color(51, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/house.png"))); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 160, 60));

        jLabel1.setFont(new java.awt.Font("Uglygoodbaddark", 3, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senior Results");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 610, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/wallpaperflare.com_wallpaper (41).jpg"))); // NOI18N
        jLabel4.setText("jLabel3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int c = 0;
        try {

            if(jtxtSID.getText().isEmpty() || jtxtAdm.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please Fill The Empty Feild.....");
            }
            else{

                String username=jtxtSID.getText();
                String password=jtxtAdm.getText();

                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
                pst = conn.prepareStatement("SELECT * FROM seniorstudent WHERE SID=?");
                pst1 = conn.prepareStatement("SELECT * FROM ssm WHERE Addmission=?");
                pst.setString(1, username);
                pst1.setString(1, password);
                rs = pst.executeQuery();
                rs2 = pst1.executeQuery();

                if(rs.next()){
                    jtxtStudentDetails.append("\t Student Details \n\n"+"================================\n\n"+
                        "\b SID:-\t"+(rs.getString(1))+"\n"+
                        "\b Name:-\t"+(rs.getString(2))+" "+(rs.getString(3))+"\n"+
                        "\b NIC:-\t"+(rs.getString(4))+"\n"+
                        "\b DOB:-\t"+(rs.getString(5))+"\n"+
                        "\b TpNo:-\t"+(rs.getString(6))+"\n"+
                        "\b Address:-\t"+(rs.getString(7))+"\n"+
                        "\b Class:-\t"+(rs.getString(8))+"\n"+
                        "\b Year:-\t"+(rs.getString(9))+"\n"+
                        "\b Gender:-\t"+(rs.getString(10))+"\n"+
                        "\b S1:-\t"+(rs.getString(11))+"\n"+
                        "\b S2:-\t"+(rs.getString(12))+"\n"+
                        "\b S3:-\t"+(rs.getString(13))+"\n"+
                        "\b S4:-\t"+(rs.getString(14))+"\n"+
                        "\b S5:-\t"+(rs.getString(15))+"\n");

                }
                if(rs2.next()){
                    jtxtStudentMarks.append("\t Student Marks Details \n\n"+"==============================\n\n"+
                        "\b SID:-\t"+(rs2.getString(1))+"\n"+
                        //"\b Name:-\t"+(rs2.getString(2))+"\n"+
                        "\b Addmission:-\t"+(rs2.getString(2))+"\n"+
                        (rs.getString(11))+":-\t"+(rs2.getString(3))+"|"+
                        " S1G:-\t"+(rs2.getString(4))+"\n"+
                        (rs.getString(12))+":-\t"+(rs2.getString(5))+"|"+
                        " S2G:-\t"+(rs2.getString(6))+"\n"+
                        (rs.getString(13))+":-\t"+(rs2.getString(7))+"|"+
                        " S3G:-\t"+(rs2.getString(8))+"\n"+
                        (rs.getString(14))+":-\t"+(rs2.getString(9))+"|"+
                        " S4G:-\t"+(rs2.getString(10))+"\n"+
                        (rs.getString(15))+":-\t"+(rs2.getString(11))+"|"+
                        " S5G:-\t"+(rs2.getString(12))+"\n"+
                        " Total Marks:-\t"+(rs2.getString(13))+"\n"+
                        " Total Marks:-\t"+(rs2.getString(14))+"\n");

                }
                else{
                    JOptionPane.showMessageDialog(this, "SID or ADDMISSION_NO is incorrect.....");
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog( Frame,"confirm if you Want to Exit","Name of the Application or Title",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jtxtStudentDetails.setText("");
        jtxtStudentMarks.setText("");
        jtxtSID.setText("");
        jtxtAdm.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            boolean complete = jtxtStudentDetails.print()&& jtxtStudentMarks.print();
            //boolean complete2 = jtxtStudentMarks.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Home m = new Home();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jtxtAdm;
    private javax.swing.JTextField jtxtSID;
    private javax.swing.JTextArea jtxtStudentDetails;
    private javax.swing.JTextArea jtxtStudentMarks;
    // End of variables declaration//GEN-END:variables
}
